name: engulfers
base: core22
version: '0.1.6'
summary: Capture all entities to win!
description: |
  Play as an symbiote of light who controls void entities set in the aftermath of an extinction causing event led by void entities. Eliminate all the void entities to win!

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  engulfers:
    command: engulfers
    extensions: [gnome]
    plugs: [home, network, removable-media, unity7]

parts:
  engulfers:
    plugin: dump
    source: ./builds/
    source-type: local
    stage-packages:
      - libglu1-mesa
      - libxcursor1
      - libxinerama1
      - libxrandr2
      - libxi6
      - libpulse0
    override-build: |
      snapcraftctl build
      chmod +x $SNAPCRAFT_PART_INSTALL/engulfers

layout:
  /usr/share/engulfers:
    bind: $SNAP/usr/share/engulfers
